var onInputCount=0,inputStart,onInputInactiveId,charactersPerMsThreshold=getQueryVariable("swiperate",.08),inactivityTimeout=getQueryVariable("inactivityto",500),tokenizeWhenInactive="true"===getQueryVariable("tokenizewheninactive","false"),enhancedResponse="true"===getQueryVariable("enhancedresponse","false"),raiseEventOnInvalidInput="true"===getQueryVariable("invalidinputevent","false"),autoFocus="true"===getQueryVariable("autofocus","false"),formatInput="true"===getQueryVariable("formatinput",
"false"),swipeonly="true"===getQueryVariable("swipeonly","false"),placeholder=getQueryVariable("placeholder",null),placeholderMonth=getQueryVariable("placeholdermonth",null),placeholderYear=getQueryVariable("placeholderyear",null),placeholderCVV=getQueryVariable("placeholdercvv",null),tokenPropName=scrubInput(getQueryVariable("tokenpropname","message"),30,"message",/^[0-9a-zA-Z]+$/),generateUniqueToken="true"===getQueryVariable("unique","false"),fullMobileKeyboard="true"===getQueryVariable("fullmobilekeyboard",
"false"),useExpiry="true"===getQueryVariable("useexpiry","false"),useCVV="true"===getQueryVariable("usecvv","false"),maskedPanFromLastToken=null,lastToken=null,ccfield,ccexpirymonth,ccexpiryyear,cccvvfield,expiry=null,isTokenized=!1,cardLabel=scrubInput(decodeURI(getQueryVariable("cardlabel","Card Number")),30,"Card Number",/^[0-9a-zA-Z\s]+$/),expiryLabel=scrubInput(decodeURI(getQueryVariable("expirylabel","Expiration Date")),30,"Expiration Date",/^[0-9a-zA-Z\s]+$/),cvvLabel=scrubInput(decodeURI(getQueryVariable("cvvlabel",
"CVV")),30,"CVV",/^[0-9a-zA-Z\s]+$/),orientation=scrubInput(getQueryVariable("orientation","default"),16,"default",/default|horizontal|vertical|custom/),cardtitle=scrubInput(decodeURI(getQueryVariable("cardtitle","Credit Card Number")),30,"Credit Card Number",/^[0-9a-zA-Z\s]+$/),expirymonthtitle=scrubInput(decodeURI(getQueryVariable("expirymonthtitle","Expiration Month")),30,"Expiration Month",/^[0-9a-zA-Z\s]+$/),expiryyeartitle=scrubInput(decodeURI(getQueryVariable("expiryyeartitle","Expiration Year")),
30,"Expiration Year",/^[0-9a-zA-Z\s]+$/),cvvtitle=scrubInput(decodeURI(getQueryVariable("cvvtitle","Card Verification Value")),30,"Card Verification Value",/^[0-9a-zA-Z\s]+$/),usemonthnames="true"===getQueryVariable("usemonthnames","false"),useexpiryfield="true"===getQueryVariable("useexpiryfield","false"),INVALID_ACCOUNT_NUMBER_ERROR_CODE="1001",INVALID_CVV_ERROR_CODE="1002",INVALID_EXPIRY_ERROR_CODE="1003",defaultExpiryGap=30,horizontalExpiryGap=12,cvvGap=12;
function nameField(a){var b=document.getElementById(a);b.value="";b.setAttribute("name",a+Math.floor(1E7*Math.random()))}function getQueryVariable(a,b){for(var c=window.location.search.substring(1).split("\x26"),d=0;d<c.length;d++){var e=c[d].split("\x3d");if(e[0]==a)return e[1]}return b?b:!1}var cssUrl=getQueryVariable("cssurl"),cssText=getQueryVariable("css");cssUrl?sanitizeCss(getCssProxyUrl()+"?cssurl\x3d"+cssUrl):cssText&&sanitizeCss(getCssProxyUrl()+"?css\x3d"+cssText);
function sanitizeCss(a){var b=getXhr();b.onreadystatechange=function(){4==b.readyState&&200==b.status&&appendSanitizedCss(b.responseText)};b.open("GET",a,!0);b.send(null)}function appendSanitizedCss(a){var b=document.getElementsByTagName("head")[0],c=document.createElement("style");c.type="text/css";c.styleSheet?c.styleSheet.cssText=a:c.appendChild(document.createTextNode(a));b.appendChild(c)}
function clearInputs(){if(isTokenized&&(useExpiry||useCVV)){isTokenized=!1;ccfield.value="";useexpiryfield?(ccexpirymonth.value="",ccexpiryyear.value=""):(ccexpirymonth.options[0].selected="selected",ccexpiryyear.options[0].selected="selected");cccvvfield.value="";var a={};a[tokenPropName]="";a.expiry="";window.parent.postMessage(JSON.stringify(a),"*")}}
function getToken(){var a=isSwipe(),b=a?"swipe":"manual",c=formatInput&&!a?ccfield.value.replace(/ /g,""):ccfield.value,d=null,e=null,g=new Date,f=null;if(a||isValidLengthAndFormat(c)){if(useExpiry&&!a)if(useexpiryfield){d=ccexpirymonth.value;if(d.match(/(^0?[1-9]$)|(^1?[1-2]$)/)&&""!==d)d=parseInt(d);else{""!==d&&(ccexpirymonth.className="error",raiseEventOnInvalidInput&&sendValidationError("Invalid Expiry",INVALID_EXPIRY_ERROR_CODE,""));return}for(var e=ccexpiryyear.value,h="",k=(new Date).getFullYear(),
l=0;20>l;++l)h=19===l?h+("(^"+k+"$)"):h+("(^"+k+"$)|"),++k;if(e.match(new RegExp(h,"g"))&&""!==e)e=parseInt(e),ccexpiryyear.className="";else{""!==e&&(ccexpiryyear.className="error",raiseEventOnInvalidInput&&sendValidationError("Invalid Expiry",INVALID_EXPIRY_ERROR_CODE,""));return}}else d=ccexpirymonth.options[ccexpirymonth.selectedIndex].value,e=ccexpiryyear.options[ccexpiryyear.selectedIndex].value,expiry=ccexpiryyear.options[ccexpiryyear.selectedIndex].value+ccexpirymonth.options[ccexpirymonth.selectedIndex].value,
"--"!==d&&(d=parseInt(d),ccexpirymonth.className=""),"--"!==e&&(e=parseInt(e),ccexpiryyear.className="");useCVV&&!a&&(f=cccvvfield.value);useExpiry&&!a&&(g.getMonth()+1>d&&g.getFullYear()===e||g.getFullYear()>e)||"--"===d||"--"===e?"--"===d||"--"===e||useexpiryfield||(ccexpirymonth.className="error",ccexpiryyear.className="error",raiseEventOnInvalidInput&&sendValidationError("Invalid Expiry",INVALID_EXPIRY_ERROR_CODE,"")):!useCVV||a||f.match(/^[0-9]{3,4}$/)?(null!==f&&f.match(/^[0-9]{4,4}$/)?cccvvfield.className=
"":null!==f&&f.match(/^[0-9]{3,3}$/)&&(cccvvfield.className=""),d=getHostUrl()+"/cardsecure/api/v1/ccn/tokenize",e=function(a){processToken(a,b,c)},a?tokenizeSwipe(c,d,e,expiry,f):tokenizeManualInput(c,d,e,expiry,f)):""!==f&&(raiseEventOnInvalidInput&&sendValidationError("Invalid CVV",INVALID_CVV_ERROR_CODE,""),""!==cccvvfield.value&&(cccvvfield.className="error"))}else maskedPanFromLastToken!==ccfield.value?(ccfield.className="error",raiseEventOnInvalidInput&&sendValidationError("Invalid Account Number",
INVALID_ACCOUNT_NUMBER_ERROR_CODE,b)):(a={},a[tokenPropName]=lastToken,a.expiry=expiry,enhancedResponse&&addEnhancedResponseFieldsToResponseObject(a,lastToken,b),window.parent.postMessage(JSON.stringify(a),"*"))}function sendValidationError(a,b,c){var d={};d[tokenPropName]="";d.expiry=void 0;d.validationError=a;enhancedResponse&&(d.token="",d.errorCode=b,d.errorMessage=a,d.entry=c);window.parent.postMessage(JSON.stringify(d),"*")}function tokenizeSwipe(a,b,c,d,e){tokenize("CZ",a,b,c,d,e)}
function tokenizeManualInput(a,b,c,d,e){tokenize("CE",a,b,c,d,e)}
function tokenize(a,b,c,d,e,g){var f=getXhr();f.onreadystatechange=function(){4===f.readyState&&200===f.status&&d(f.responseText)};f.open("POST",c,!0);f.setRequestHeader("Content-Type","application/json");c={};c="CZ"===a?{devicedata:b,source:"iToke",encryptionhandler:"RSA",unique:!1}:{account:b,source:"iToke",encryptionhandler:null,unique:!1,expiry:e,cvv:g};"CR"===a&&(c.encryptionhandler="RSA");generateUniqueToken&&(c.unique=!0);f.send(JSON.stringify(c))}
function getPublicKey(a,b,c){var d=getXhr();d.onreadystatechange=function(){if(4===d.readyState)if(200===d.status&&-1===d.responseText.indexOf("action\x3dER")){var a=getData(d.responseText),a=decodeURIComponent(a.replace(/\+/g,"%20"));b(a)}else c()};d.open("POST",a,!0);d.setRequestHeader("Content-Type","application/x-www-form-urlencoded");d.send("action\x3dKG\x26data\x3d\x26encryptionHandler\x3dRSA")}
function isValidLengthAndFormat(a){var b=a.length;if(-1<a.indexOf("/")){var c=a.substring(0,a.indexOf("/"));a=a.substring(a.indexOf("/")+1);var d=c.length;return 10<=b&&27>=b&&isNumeric(c)&&isNumeric(a)&&(8===d||9===d)}return 14<=b&&19>=b&&isNumeric(a)&&luhnCheck(a)}
function isSwipe(){var a=ccfield.value;return 19<a.length&&(matchT1(a)||matchT2(a)||isIDTechSREDSwipe(a)||0===a.indexOf("DFEE25")&&isValidHex(a)||(0===a.indexOf("%B")||0===a.indexOf(";")||0===a.indexOf("M1"))&&10<=a.split("|").length-1)}function isIDTechSREDSwipe(a){return 0===a.indexOf("02")&&isValidHex(a.substr(0,16))&&endsWith(a,"03")}function isValidHex(a){return null!=a.match(/\b[0-9A-Fa-f]+\b/gi)}function isNumeric(a){return!isNaN(parseFloat(a))&&isFinite(a)}
function endsWith(a,b){var c=b.length;return a.length>=c?a.substr(a.length-c)===b:!1}function luhnCheck(a){var b=a.substring(0,a.length-1);a=parseInt(a.charAt(a.length-1),10);for(var c=0,d=!0,e=b.length-1;0<=e;e--){var g=parseInt(b.charAt(e),10);d&&(g*=2,g=9<g?g-9:g);c+=g;d=!d}return a===9*c%10}function getHostUrl(){var a=window.location.port,b=window.location.protocol+"//"+window.location.hostname;a&&(b=b+":"+a);return b}
function getCssProxyUrl(){var a=getHostUrl(),b=window.location.pathname.split("/");return a+"/"+b[1]+"/css-sanitize"}function monthNameToNumber(a){return{january:1,february:2,march:3,april:4,may:5,june:6,july:7,august:8,september:9,october:10,november:11,december:12}[a.lowercase()]}function monthNumberToName(a){return{1:"January",2:"February",3:"March",4:"April",5:"May",6:"June",7:"July",8:"August",9:"September",10:"October",11:"November",12:"December"}[a]}
function getXhr(){var a=["Msxml2.XMLHTTP.6.0","Msxml2.XMLHTTP.3.0","Msxml2.XMLHTTP"];if(window.ActiveXObject){for(var b=0;b<a.length;b++)try{return new ActiveXObject(a[b])}catch(c){}throw Error("XMLHttpRequest not supported");}if(window.XMLHttpRequest)return new XMLHttpRequest;throw Error("XMLHttpRequest not supported");}
function processToken(a,b,c){a=getData(a);ccfield.value=getMaskedPan(c,a);maskedPanFromLastToken=ccfield.value;lastToken=a;expiry=isIDTechSREDSwipe(c)?getExpiryFromSwipe(c):expiry;c={};c[tokenPropName]=a;null!==expiry&&(c.expiry=expiry);enhancedResponse&&addEnhancedResponseFieldsToResponseObject(c,a,b);isTokenized=!0;window.parent.postMessage(JSON.stringify(c),"*");ccfield.style.borderColor=""}
function addEnhancedResponseFieldsToResponseObject(a,b,c){var d=getErrorResponseDetails(b);null==d?(a.token=b,a.errorCode="0",a.errorMessage=""):(a.token="",a.errorCode=d.errorCode,a.errorMessage=d.errorMessage);a.entry=c;return a}function getErrorResponseDetails(a){a=decodeURIComponent(a);a=/^([0-9]{4})(::)(.*)$/.exec(a);return null!=a?{errorCode:a[1],errorMessage:a[3].replace(/\+/g," ")}:null}
function getMaskedPan(a,b){var c;if(isSwipe()||-1!==a.indexOf("/")){if(!isSwipe()&&-1<a.indexOf("/"))return b=a.substring(0,a.indexOf("/")),a=a.substring(a.indexOf("/")+1),a=4<a.length?Array(a.length-3).join("*")+a.substring(a.length-4):"****",b+"/"+a;if(c=matchT1(a))return b=c[1],a=b.substr(2,2),c=b.substr(b.length-5,4),a+Array(b.length-8).join("*")+c;if(c=matchT2(a))return b=c[1],a=b.substr(1,2),c=b.substr(b.length-5,4),a+Array(b.length-7).join("*")+c;a=b.substr(1,2);c=b.substr(b.length-5,4);return a+
Array(b.length-7).join("*")+c}return a.substring(0,2)+Array(a.length-6).join("*")+a.substring(a.length-4,a.length)}function getExpiryFromSwipe(a){var b=null,c=matchT1(a);null!==c&&(b=nullIfUndefined(c[2]));null===b&&(a=matchT2(a),null!==a&&(b=nullIfUndefined(a[2])));return b}function matchT1(a){return a.match(/(%.[0-9]{2}.{7,13}[0-9]{4}\^).{2,26}\^([0-9]{4})?/)}function matchT2(a){return a.match(/(;[0-9]{2}.{7,13}[0-9]{4}=)([0-9]{4})?/)}function nullIfUndefined(a){return void 0===a?null:a}
function onCCNumFieldKeyUp(){var a=formatInput?ccfield.value.replace(/ /g,""):ccfield.value;null!==maskedPanFromLastToken?a===maskedPanFromLastToken||isValidLengthAndFormat(a)?ccfield.className="":ccfield.className="error":"error"===ccfield.className&&isValidLengthAndFormat(a)&&(ccfield.className="")}function getData(a){a=JSON.parse(a);return a.hasOwnProperty("token")?a.token:""}
function format(a){var b=ccfield.value[0];if("input"===a.type&&("2"===b||"3"===b||"4"===b||"5"===b||"6"===b)){var c=ccfield.value,d=c.replace(/ /g,"");a=ccfield.selectionStart;var e=ccfield.value.length;if(1<d.length&&19>=d.length&&isNumeric(d)){if(b=0===d.indexOf("34")||0===d.indexOf("37")?/(\d{1,4})(\d{1,6})?(\d{1,5})?/:/(\d{1,4})(\d{1,4})?(\d{1,4})?(\d{1,4})?(\d{1,3})?/,d=d.match(b))if(d.shift(),ccfield.value=d.join(" ").trim(),a!==e)e=c.substring(0,a),c=0,-1===e.indexOf(" ")&&(d=e.match(b))&&
(d.shift(),c=(d.join(" ").trim().match(/ /g)||[]).length),setCaretPosition(a+c)}else 9<=d.length&&27>=d.length&&-1<d.indexOf("/")&&-1<ccfield.value.indexOf(" ")&&(ccfield.value=d,a!==e&&(e=c.substring(0,a),c=(e.match(/ /g)||[]).length,setCaretPosition(a-c)))}}function setCaretPosition(a){if(ccfield.createTextRange){var b=ccfield.createTextRange();b.move("character",a);b.select()}else ccfield.selectionStart&&ccfield.setSelectionRange(a,a)}
function scrubInput(a,b,c,d){return a&&0!==a.length&&a.length<=b&&a.match(d)?a:c}function onInput(a){onInputInactiveId&&clearTimeout(onInputInactiveId);inputStart||(inputStart=(new Date).getTime());onInputCount++;onInputInactiveId=setTimeout(onInputInactive,inactivityTimeout);formatInput&&format(a);clearInputs()}
function onInputInactive(){if(tokenizeWhenInactive)getToken();else{var a=(new Date).getTime()-inputStart,a=onInputCount/a;0<charactersPerMsThreshold&&a>=charactersPerMsThreshold?getToken():swipeonly&&(document.getElementById("ccnumfield").value="")}inputStart=null;onInputCount=0}
function addExpiryField(){var a=document.getElementById("tokenform");ccexpirymonth=document.getElementById("ccexpiryfieldmonth");ccexpirymonth.title=expirymonthtitle;ccexpirymonth.oninput=onInput;ccexpirymonth.setAttribute("type","text");placeholderMonth&&(ccexpirymonth.placeholder=scrubInput(decodeURIComponent(placeholderMonth),30,"",/^[0-9a-zA-Z\s.#]+$/));a.insertBefore(ccexpirymonth,cccvvfield);tokenizeWhenInactive||(ccexpirymonth.onblur=getToken);ccexpiryyear=document.getElementById("ccexpiryfieldyear");
ccexpiryyear.setAttribute("type","text");ccexpiryyear.title=expiryyeartitle;ccexpiryyear.oninput=onInput;placeholderYear&&(ccexpiryyear.placeholder=scrubInput(decodeURIComponent(placeholderYear),30,"",/^[0-9a-zA-Z\s.#]+$/));var b=document.createElement("label");b.innerText="/";"default"===orientation&&(ccexpiryyear.style.marginLeft=defaultExpiryGap/2-2+"px",ccexpirymonth.style.marginRight=defaultExpiryGap/2-2+"px");"horizontal"===orientation&&(ccexpiryyear.style.marginLeft=horizontalExpiryGap/2-2+
"px",ccexpirymonth.style.marginRight=horizontalExpiryGap/2-2+"px",useCVV&&(ccexpiryyear.style.marginRight=horizontalExpiryGap+"px"));a.insertBefore(ccexpiryyear,cccvvfield);tokenizeWhenInactive||(ccexpiryyear.onblur=getToken);var c=document.createElement("br"),d=document.createElement("label");d.innerText=expiryLabel;d.id="ccexpirylabel";"horizontal"===orientation&&(d.style.marginRight=horizontalExpiryGap+"px");var e=document.createElement("br");"custom"!==orientation&&a.insertBefore(c,ccexpirymonth);
a.insertBefore(d,ccexpirymonth);"custom"!==orientation&&a.insertBefore(e,ccexpirymonth);"vertical"===orientation&&(b=document.createElement("br"));a.insertBefore(b,ccexpiryyear)}
function addExpiry(){var a=document.getElementById("tokenform");ccexpirymonth=document.createElement("select");ccexpirymonth.title=expirymonthtitle;ccexpirymonth.id="ccexpirymonth";ccexpirymonth.oninput=onInput;a.insertBefore(ccexpirymonth,cccvvfield);tokenizeWhenInactive||(ccexpirymonth.onblur=getToken);var b=document.createElement("option");b.text="--";b.value="--";ccexpirymonth.add(b);for(i=1;12>=i;++i)b=document.createElement("option"),b.text=usemonthnames?monthNumberToName(i):10>i?"0"+i:i,b.value=
i,ccexpirymonth.add(b);ccexpiryyear=document.createElement("select");ccexpiryyear.title=expiryyeartitle;ccexpiryyear.id="ccexpiryyear";ccexpiryyear.oninput=onInput;"default"===orientation&&(ccexpiryyear.style.marginLeft=defaultExpiryGap+"px");"horizontal"===orientation&&(ccexpiryyear.style.marginLeft=horizontalExpiryGap+"px",useCVV&&(ccexpiryyear.style.marginRight=horizontalExpiryGap+"px"));a.insertBefore(ccexpiryyear,cccvvfield);tokenizeWhenInactive||(ccexpiryyear.onblur=getToken);b=document.createElement("option");
b.text="--";b.value="--";ccexpiryyear.add(b);var c=(new Date).getFullYear();for(i=0;20>i;++i)b=document.createElement("option"),b.text=c,b.value=c,ccexpiryyear.add(b),c+=1;b=document.createElement("br");c=document.createElement("label");c.innerText=expiryLabel;c.id="ccexpirylabel";"horizontal"===orientation&&(c.style.marginRight=horizontalExpiryGap+"px");var d=document.createElement("br");"custom"!==orientation&&a.insertBefore(b,ccexpirymonth);a.insertBefore(c,ccexpirymonth);"custom"!==orientation&&
a.insertBefore(d,ccexpirymonth);"vertical"===orientation&&(b=document.createElement("br"),a.insertBefore(b,ccexpiryyear))}
function addCVV(){var a=document.getElementById("tokenform");cccvvfield=document.getElementById("cccvvfield");cccvvfield.title=cvvtitle;cccvvfield.oninput=onInput;placeholderCVV&&(cccvvfield.placeholder=scrubInput(decodeURIComponent(placeholderCVV),30,"",/^[0-9a-zA-Z\s.#]+$/));cccvvfield.setAttribute("type","text");tokenizeWhenInactive||(cccvvfield.onblur=getToken);var b=document.createElement("br");"horizontal"===orientation&&useExpiry||"custom"===orientation||a.insertBefore(b,cccvvfield);b=document.createElement("label");
b.innerText=cvvLabel;b.id="cccvvlabel";"horizontal"===orientation&&useExpiry&&(b.style.marginRight=cvvGap+"px");var c=document.createElement("br");if("horizontal"===orientation&&useExpiry){a.insertBefore(b,ccexpirymonth.previousElementSibling);var d=cccvvfield.getBoundingClientRect();b.style.position="absolute";b.style.left=d.x+"px"}else a.insertBefore(b,cccvvfield);"horizontal"===orientation&&useExpiry||"custom"===orientation||a.insertBefore(c,cccvvfield)}
function onLoad(){ccfield=document.getElementById("ccnumfield");cccvvfield=document.getElementById("cccvvfield");var a=document.getElementById("ccnumfield");a.size=formatInput?24:19;a.oninput=onInput;a.onpropertychange=a.oninput;a.title=cardtitle;tokenizeWhenInactive||(a.onblur=getToken);a.onkeyup=onCCNumFieldKeyUp;fullMobileKeyboard&&(a.type="text");autoFocus&&a.focus();placeholder&&(a.placeholder=scrubInput(decodeURIComponent(placeholder),30,"",/^[0-9a-zA-Z\s.#]+$/));a=document.getElementById("tokenform");
useExpiry&&(useexpiryfield?addExpiryField():addExpiry());useCVV&&addCVV();if(useExpiry||useCVV){var b=document.createElement("label");b.innerHTML=cardLabel;b.id="cccardlabel";var c=document.createElement("br");a.insertBefore(b,ccfield);"custom"!==orientation&&a.insertBefore(c,ccfield)}};